name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
         IMAGE_TAG=904233102889.dkr.ecr.ap-south-1.amazonaws.com/nodesample:latest
         docker build -t $IMAGE_TAG .
         docker push $IMAGE_TAG
        env:
         AWS_REGION: ap-south-1
         AWS_ACCOUNT_ID: 904233102889
         IMAGE_REPO_NAME: nodesample
        
